name: Update Terminal Animation

on:
  schedule:
    - cron: "*/30 * * * *"  # her 30 dakikada bir çalışır
  workflow_dispatch:        # manuel tetikleme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Generate SVG
        run: python generate.py

      - name: Commit & Push
        run: |
          git config --global user.name "pulse256"
          git config --global user.email "actions@github.com"
          git add terminal.svg
          git commit -m "update terminal animation" || exit 0
          git push